# Snakemake config
params:
    jellyfish: "-C -s 1G -c 2 --out-counter-len=2 -L 2"
resources:
    map:
        cpu: 8
        mem_mb: 16000
        time_min: 120
    jf:
        cpu: 2
        mem_mb: 8000
        time_min: 480
